name: shared_app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  shared:
    path: ../../../shared
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^9.2.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  dio: ^5.4.1
  simple_animations: ^5.0.2
  timeago_flutter: ^3.6.0
  hive: ^2.2.3
  path_provider: ^2.1.1
  provider: ^6.1.1
  logging: ^1.2.0
  dino: ^1.0.0-pre.1
  font_awesome_flutter: ^10.7.0
  cross_file: ^0.3.4+1
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
